### PR TITLE
Fix RtlHardcoded warning for TaskbarController

### PR DESCRIPTION
**Pull request by utzcoz**
Test: manually
Test: `./gradlew test`

### CODE REVIEW

**Comment by farmerbb** [comment]
I also think this will break the app on actual right-to-left locales due to the layouts that the app loads via that preference also being hardcoded for the different positions on screen.

**Comment by utzcoz** [comment]
@farmerbb On most occasion, the `Gravity.START` is same as `Gravity.LEFT`, but `Gravity.START` can adapt for the real `left` position for RTL locales. There is an example created by `AOSP`: [Replace left/right with start/end for Gravity / LayoutParams / Padding](https://github.com/aosp-mirror/platform_frameworks_base/commit/aac0d4ed026d1cfbcf3fa81c6e4eb96f4347ca17).

**Comment by utzcoz** [comment]
@farmerbb I will test it with RTL locales to see the result.

**Comment by utzcoz** [comment]
@farmerbb , you're right, thanks for your advice. There are `left` and `right` used by `xml` and other source files. If need, I can try to support RTL for other windows and views; if not, I will close this pr.

**Comment by utzcoz** [comment]
@farmerbb , I just change all "LEFT/RIGHT" to "START/END" in source files and xml files, the location is not correctly with RTL locales. Looks like there are code to calculate the location. I will close this par, and maybe to try it after large coverage tests.

**Pull request closed without merging**
