### PR TITLE
Add basic unit test structure

### PR DESCRIPTION
**Pull request by utzcoz**
Selecting robolectric as unit test library to test UI on JVM. We use the
robolectric version 4.3.1, that supports to latest Android Q(final). But
it requires Java 9 to run the tests, so to avoid this problem, we assign
the sdk to 28 in robolectric.properties for almost all tests, and
leaving Android 10 specific features left to ease the usage of
robolectric.

Now we add a test example for `U.java` `getTaskbarPosition` function.

For check the tests result, we can execute `./gradlew test` on the top
code directory, or use ctrl + shift + F10 in test file to execute unit
test in Android Studio.

For robolectric Java 9 discussion, we can see the link [SO Does Robolectric require Java 9?](https://stackoverflow.com/questions/56821193/does-robolectric-require-java-9)

@farmerbb Taskbar is a large app now, maybe we should integrate tests to ensure
app function. And unit test is a good start.

### CODE REVIEW

**Comment by utzcoz** [comment]
@farmerbb Also unit test can run on pure JVM on the CI machine, and we can use it to check every modification.

**Comment by utzcoz** [comment]
The test result is generate to `app/build/reports/tests/testFreeDebugUnitTest/`.

**Comment by farmerbb** [comment]
Thanks for adding this.  I'm pretty familiar with Robolectric and I agree that it's the right choice for testing this project.  (I hadn't done any unit testing for Taskbar just because it's so tightly coupled with the Android framework, but there is quite a bit that could be tested here.)

I'll add the necessary stuff to integrate this with CI soon.  Thanks again!

**Comment by utzcoz** [comment]
Okay, I will continue to do little code clean with relative tests.

**Pull request merged**
